{
 "title": "Orders API Dashboard",
 "tags": [
  "orders-api",
  "flask"
 ],
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total[5m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{http_status=~\"5..\"}[5m]))",
     "legendFormat": "Errors/sec"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "timeSeries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[5m])) by (endpoint,method,http_status)",
     "legendFormat": "{{endpoint}} {{method}} {{http_status}}"
    }
   ]
  },
  {
   "title": "Latency (90th percentile)",
   "type": "timeSeries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "DB Failures (/orders 500s)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{endpoint=\"/orders\", http_status=\"500\"}[5m]))",
     "legendFormat": "DB Failures"
    }
   ]
  }
 ]
}