apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL29yZGVyczpvcmRlcnNwYXNzQGhvc3QuZG9ja2VyLmludGVybmFsOjU0MzIvb3JkZXJzZGI=
